# Generated by Django 5.2.8 on 2025-12-22 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_affiliateaccounts_productlinks_racks_and_more'),
    ]

    operations = [
        # (opsional) hapus unique_together productlinks saja
        migrations.AlterUniqueTogether(
            name='productlinks',
            unique_together=None,
        ),

        # hapus field
        migrations.RemoveField(
            model_name='rackitems',
            name='product_link',
        ),
        migrations.RemoveField(
            model_name='rackitems',
            name='rack',
        ),
        migrations.RemoveField(
            model_name='productlinks',
            name='user',
        ),
        migrations.RemoveField(
            model_name='racks',
            name='user',
        ),

        # hapus model
        migrations.DeleteModel(name='CampaignTemplates'),
        migrations.DeleteModel(name='ProductLinks'),
        migrations.DeleteModel(name='RackItems'),
        migrations.DeleteModel(name='Racks'),
    ]
