# Generated by Django 5.2.8 on 2025-12-22 09:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('racks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignTemplates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('platform', models.CharField(choices=[('x', 'X / Twitter'), ('facebook', 'Facebook'), ('instagram', 'Instagram'), ('threads', 'Threads'), ('tiktok', 'TikTok'), ('whatsapp', 'WhatsApp')], max_length=50)),
                ('content_template', models.TextField(help_text='Gunakan placeholder seperti {product_name}, {affiliate_link}, {rack_name}')),
                ('image_template_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('related_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.productlinks')),
                ('related_rack', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='racks.racks')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_templates', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
