# Generated by Django 5.2.8 on 2025-12-27 09:21

import django.db.models.deletion
import products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=products.models.product_image_path)),
                ('is_primary', models.BooleanField(default=False, help_text='Menandai gambar utama produk')),
                ('order', models.PositiveIntegerField(default=0, help_text='Urutan tampilan gambar')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_images', to='products.productlinks')),
            ],
            options={
                'ordering': ['order', 'created_at'],
                'indexes': [models.Index(fields=['product_link'], name='products_pr_product_f25a47_idx')],
            },
        ),
    ]
